version: '3.8'

services:
  # MySQL Master
  mysql_master:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysqlezequiel1_
      MYSQL_DATABASE: Mateando_Juntos
    ports:
      - "3306:3306"
    volumes:
      - mysql_master_data:/var/lib/mysql
    networks:
      - backend
    env_file:
      - .env.development  # Asumiendo que tienes este archivo con las credenciales

  # PHP & Apache
  web:
    build:
      context: .  # Apunta al directorio actual donde est치 el Dockerfile
      dockerfile: Dockerfile
    volumes:
      - ./Backend:/var/www/html/Backend  # C칩digo PHP en Backend
      - ./Frontend:/var/www/html/Frontend  # C칩digo HTML y frontend en Frontend
      - ./UsersUploads:/var/www/html/UsersUploads  # Volumen para im치genes subidas
    ports:
      - "8080:80"
    networks:
      - backend
      - frontend

volumes:
  mysql_master_data:

networks:
  backend:
  frontend:
